# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handyHelper', '0003_remove_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='handyHelper.User'),
            preserve_default=False,
        ),
    ]
